In [1]:
import pandas as pd

In [2]:
data_og=pd.read_csv("apache-ant-og.csv")

In [3]:
data_og[:5]

projectname classification  \
0  apache-ant-1.7.0         DEFECT   
1  apache-ant-1.7.0         DEFECT   
2  apache-ant-1.7.0         DEFECT   
3  apache-ant-1.7.0         DEFECT   
4  apache-ant-1.7.0         DEFECT   

                                         commenttext  
0            // FIXME formatters are not thread-safe  
1  // XXX: (Jon Skeet) The comment "if it hasn't ...  
2  // I hate to admit it, but we don't know what ...  
3  // Just a note: StarTeam has a status for NEW ...  
4  // the generated classes must not be added in ...

In [4]:
data_corr=pd.read_csv("apache-ant-corr.csv")

In [5]:
data_corr[:5]

ID       projectname classification  \
0   0  apache-ant-1.7.0         DEFECT   
1   1  apache-ant-1.7.0         DEFECT   
2   2  apache-ant-1.7.0         DEFECT   
3   3  apache-ant-1.7.0         DEFECT   
4   4  apache-ant-1.7.0         DEFECT   

                                            Abstract label  
0            // FIXME formatters are not thread-safe   yes  
1  // XXX: (Jon Skeet) The comment "if it hasn't ...   yes  
2  // I hate to admit it, but we don't know what ...   yes  
3  // Just a note: StarTeam has a status for NEW ...   yes  
4  // the generated classes must not be added in ...   yes

In [6]:
data_corr.shape

(4098, 5)

In [7]:
data_corr.loc[data_corr.label=='yes', 'label'].count()
#(data_corr.label=='yes').sum()

135

In [8]:
data_corr.query('label == "no"').label.count()
#data_corr.label.value_counts().no  
#Note value_counts() is used only with series type of data

3963

In [28]:
comments=data_corr['Abstract']

In [50]:
comments=comments.to_frame()

In [51]:
comments[:5]

Abstract
0            // FIXME formatters are not thread-safe
1  // XXX: (Jon Skeet) The comment "if it hasn't ...
2  // I hate to admit it, but we don't know what ...
3  // Just a note: StarTeam has a status for NEW ...
4  // the generated classes must not be added in ...

In [11]:
import tensorflow as tf

In [14]:
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np

In [66]:
embedding_fn = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [65]:
print(embedding_fn(["Hello world"]))

tf.Tensor(
[[-2.60742642e-02 -8.46000165e-02 -2.67866217e-02  5.67842275e-02
   6.19704723e-02  3.82260159e-02  2.01149341e-02  2.74087600e-02
   8.69831964e-02  3.07917856e-02  4.10411730e-02  2.55183429e-02
   9.65186744e-04  5.89279719e-02  4.00954112e-02  4.67089340e-02
  -3.31279561e-02  4.07041609e-02 -1.19929705e-02 -4.76170555e-02
  -8.29668250e-03  7.05467463e-02  4.84353630e-03  8.09824839e-02
  -5.70177287e-02 -6.43551499e-02  6.97147325e-02 -6.98838457e-02
   2.64606178e-02 -2.35220529e-02  5.52375242e-02  4.91363965e-02
   5.69897220e-02 -6.10719360e-02  3.60850990e-02  2.32446156e-02
   5.60175255e-02 -1.09551996e-02  4.21308316e-02 -1.76953934e-02
   7.12434668e-03  2.04703063e-02 -7.10126385e-02 -8.45577493e-02
   4.36058566e-02  4.79397736e-02 -9.01802033e-02 -6.87343776e-02
   1.27959633e-02  1.62498504e-02 -4.83130850e-02  3.08831818e-02
   7.43837189e-03  3.39155644e-02  3.32343951e-02  4.33182456e-02
   6.36333525e-02  4.92026806e-02 -2.83108316e-02  8.13511573e-03

In [52]:
small_data=comments[:50]

In [87]:
for index, rows in small_data.iterrows(): 
    # Create list for the current row 
    my_list =[rows.Abstract] 
    embeddings=embedding_fn(my_list)

In [88]:
embeddings

<tf.Tensor: shape=(1, 512), dtype=float32, numpy=
array([[ 4.31705341e-02, -7.59132355e-02, -1.59662776e-02,
         3.30861248e-02,  4.94060665e-02, -3.84210125e-02,
        -5.58449365e-02, -6.20024167e-02,  6.13197498e-02,
         5.69080040e-02, -1.15657430e-02,  2.07780115e-03,
        -2.42554676e-02,  9.42547247e-02, -3.36250812e-02,
         4.90109250e-02,  1.72656830e-02,  2.98889931e-02,
        -2.86848564e-02,  2.64009237e-02, -7.20078945e-02,
         1.70208570e-02,  6.36027977e-02,  1.41150169e-02,
        -7.36694187e-02,  6.95567811e-03, -1.34305134e-02,
        -4.52557579e-02,  5.96334226e-02,  4.76884581e-02,
         2.20036805e-02,  3.61769907e-02,  1.28380600e-02,
        -9.98416170e-03, -3.18524614e-02,  1.96579639e-02,
         6.08833767e-02, -1.65448058e-02,  3.27451378e-02,
        -3.16281505e-02,  2.00991649e-02,  1.02728475e-02,
         6.21172860e-02,  7.81422853e-02,  7.94227142e-03,
        -2.77805477e-02,  1.62380375e-02, -7.96397775e-03,
      

In [89]:
for index, rows in comments.iterrows(): 
    # Create list for the current row 
    my_list =[rows.Abstract] 
    all_embeddings=embedding_fn(my_list)

In [ ]:
all_embeddings